### ISSUE TITLE
Waypoint nav no success indicator

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#103]
Waypoint navigator returns None instead of indicating success when reaching waypoint

**Comment by flamma7** [comment]
Solved with a hack via proximity to goal point in latest jianshi branch

**Comment by DrYerzinia** [comment]
Solved via fixing the actual problem.  Which I created and git blamed myself for in a massive self own.
@flamma7 Do we want to change how the system works because right now we are using polling in the state machine all over the place.  Not as simple as modifying block on reaching pose.

**Comment by flamma7** [comment]
Did the SM polling get resolved? I noticed in z_place_localizer branch we are still calling self.checked_reach_pose() in block_on_reaching_pose(). We have another movement function called go_to_pose_non_blocking() which also calls self.checked_reached_pose(), perhaps for this we could have it check the status of the goal object instead of measuring distance, this way the waypoint nav always determines if we've actually reached the goal
