### ISSUE TITLE
New Buoys In Sim

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#11]
Three sided dice with 3 different "zombies"

These can be based on the current dice models.
Need DAE visual model.  Need to figure out how to get textures to work in gazebo for vampire images.
Need to add node to spin the dice.  Need to add revolute joint to the URDF for this.  See the roulette obstacle for and example.

**Comment by skhadem** [comment]
https://www.youtube.com/watch?v=It530TOCTbM
