### ISSUE TITLE
Start gate in sim 2019

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#12]
Create a model of the New Start Gate.
Export DAE for visual model
Export STL for collision model
Create URDF of model.  This can be a static element rather than having physics as we don't expect to be crashing into it intentionally.

**Comment by flamma7** [comment]
Could one of you add the 3rd pole to the SG? I think Ryan just designed the droppers task and is planning on designing a simple octagon for the sim

**Comment by DrYerzinia** [comment]
Done
