### ISSUE TITLE
combine object assets into model folder

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#14]
urdf's, meshes, and textures for object models should all be hosted in the models folder. desired structure is:

- models
  * \<object1 name>
      - model.dae
      - model.urdf
      - all other object assets
  * \<object2 name>
      - model.dae
      - model.urdf
      - all other object assets

**Comment by DrYerzinia** [comment]
what about shared assets?

- models
  - shared
     - shared.dae
