### ISSUE TITLE
Sensor Fusion repeat-ability test

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#22]
We want to do some form of test on the accuracy of our sensor fusion.  We should have the sub run through some tasks and then return to 0, 0.  We can compare where it is to where it was when it started and characterize the drift in the sensor fusion over time with realistic motions.

We want to figure out which actions cause our odometry to drift a lot, for example, moving too fast, ramming dice.  Hard pitchs/rolls.

**Comment by skhadem** [comment]
Already done
