### ISSUE TITLE
Filtering Pose in GatePnP causes bad estimates

### ISSUE THREAD

**Issue by DrYerzinia** [CU-Robosub/cusub#29]
Pose filtering needs to be moved from GatePnP to Mapper.
We are filtering the pose estimates when they are relative poses in the camera frame so as we move forward that relative pose is changing and your moving average filter is actually lagging the results and introducing error.
Moving it to the mapper after its been transformed to odom we get the data that is consistent as we move so filtering increases accuracy.

**Comment by flamma7** [comment]
Same as #75

**Comment by skhadem** [comment]
Duplicates #75

**Comment by skhadem** [comment]
#75
