### ISSUE TITLE
Optimize PNP classical gate finding code.

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#30]
TF lookups are late for 2 reasons:
queue_size needs to be lowered: easy to fix 
optimize the overall pnp algorithm:
  - benchmark the heaviest part of the algorithms
  - streamline what can be and see if there are any acceptable sacrifices
  - look into opencl optimizations for opencv code ( I don't think we want to write our own opencl code)
  - some basic documentation of how the algorithm is executing. (aka some pseudo code)
  - possible migration to c++ code? (I don't think this will do the trick, python is pretty optimized as is probably just need to restructure a bit)

**Comment by skhadem** [comment]
@flamma7 can this be closed out?

**Comment by skhadem** [comment]
@flamma7 closing this because new algorithm seems to be killing it
