### ISSUE TITLE
Pathmarker classical computer vision

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#37]
Create CV server for classical analysis of path-marker to get a the vector it is directing us to follow.
Create a class for the Pathmarker in Darknet so we can get detection's of it.

**Comment by skhadem** [comment]
Bagged data exists, going to try watershed + contour detection to get a simple BB

**Comment by skhadem** [comment]
https://drive.google.com/drive/u/1/folders/1XH2EirnteQu2QCEwrjTuaP72-nDnHEY7

**Comment by DrYerzinia** [comment]
@flamma7, you consider this done/functional?  Or should we test at divewell?

**Comment by flamma7** [comment]
We should test the path_orient server in the divewell
