### ISSUE TITLE
Change search.py transitions

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#50]
The search objective currently has 2 outcomes: ['success', 'aborted'] change the transitions to be a little more descriptive ['obj_found', 'obj_not_found'] or something of the nature. Because it is a little unintuitive to realize that we _want_ the search objective to be aborted. Being aborted is successful, it means we're moving on to the next state in the task statemachine

**Comment by skhadem** [comment]
@flamma7 The reason the generic outcomes were used was to be able to use Simple Action State and be able to directly call actionlib, is the plan to not use actionlib anymore?

**Comment by flamma7** [comment]
Right the confusion arises when technically "aborted" is success for the search task. In start gate for example, when we see get the first pose of the gate, we abort the search task. If we reach the prior pose without being aborted it means our prior was too bad. So for new members starting with start gate may find this confusing. No I don't think an actionlib architecture in the SM would provide too many benefits b/c what would an actionlib client do with the updates?

**Comment by skhadem** [comment]
Yeah I agree, only thing that I could see with actionlib from my limited understanding is it's robust to preemption, but our server seems to handle that well
