### ISSUE TITLE
Move Leviathan drivers into the leviathan description package?

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#58]
Lets keep everything needed for the leviathan model to run within one package.

Other option is to have a separate cusub_gazebo_drivers package instead that will include the drivers for both Triton and Leviathan. With as much cross over as possible, such as:
depth_sensor
motor_control
z_odom_repub

**Comment by DrYerzinia** [comment]
I think it makes sense to do a gazebo drivers, most of the stuff is shared it just needs to be a bit more modularized.
