### ISSUE TITLE
Fix namespacing so we can launch multiple subs

### ISSUE THREAD

**Issue by DrYerzinia** [CU-Robosub/cusub#68]
Current large amounts of the codespace lack subname level namespacing.

We don't want to hardcode the subname i.e. /leviathan cause most of our code is generic to be applied to multiple sub so it needs to be definable in the launch file.

It looks like hard coded pub/sub topic strings don't inherit the namespace from the launch file group, so there needs to be a way to get this into these nodes.

**Comment by belgiumkansas** [comment]
This is part of a much bigger issue which is standardizing our name spacing with the new package organization. Trying to keep them as similar as possible to allow intuitive navigation of topic spaces
