### ISSUE TITLE
Grave pulling obstacle

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#7]
We need a casket with a vampire in it.  Potentially 2 separate obstacles.  If we need to remove the vampire some type of gazebo gripper simulation will be required.  If we just do the part where we move the caskets into the sun we can do that with basic collision detection.

Need DAE for visual
Need STL for collision
Basic URDF with physics.

**Comment by DrYerzinia** [comment]
Should we make the vampires grabable?

**Comment by skhadem** [comment]
Sorry, just saw this comment, will leave open
