### ISSUE TITLE
Configurable Bag File Grabber

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#71]
We need a launch file that's easy to configure that can bag different topics quickly. As in, this run we want to just bag occam0 & downcam or we want to bag all cameras to get nonstop bagging of an obstacle.

**Comment by belgiumkansas** [comment]
This will have to happen after the namespace issue is resolved #68

**Comment by flamma7** [comment]
As you will note in the most recent pull request, when bagging simulated data the namespacing of /leviathan/ before all of the topics is implemented
