### ISSUE TITLE
Redundant Directory Nomenclature

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#73]
cusub
-> cusub_cortex
-> cusub_documentation
-> cusub_perception
-> cusub_sim

What are the reasons for the prepension of "cusub_". Each of these directories themselves are not ros-packages, so there would not be naming conflicts among ros packages if we were to shorten the name from "cusub_cortex" to "cortex."

**Comment by belgiumkansas** [comment]
Keeping the folders named after the meta-packages avoids confusion of calling packages that are a generic part of ros (aka perception) or calling a package that don't exist. Its about keeping the code readable and consistent for everyone.
