### ISSUE TITLE
Dropping garlic buckets

### ISSUE THREAD

**Issue by belgiumkansas** [CU-Robosub/cusub#8]
Dropper Obstacle.  One will need lid.  Collision detection in gazebo should be sufficient for our actuation of lid.

Need models of boxes and Lids:
DAEs for visual
STL for collision
URDFs describing obstacles.  Not sure what joint type will work best for lid or if best implemented as 2 seperate obstacles.  May cause problems with low simulation ode solver settings.

**Comment by DrYerzinia** [comment]
Should I make the lever work???

**Comment by skhadem** [comment]
Not a bad thought, but I think until we get the main objectives nailed, no reason to enhance that much
