### ISSUE TITLE
Magic LEDs

### ISSUE THREAD

**Issue by DrYerzinia** [CU-Robosub/cusub#83]
Square of LEDs on PVC hanging from edge of pool at known position
  - Use color threshold to quickly (low compute) ID 4 led positions
  - Use solvePnP to extract sub pose
    - Improvements
      - Create pixel level distortion map for Occam
      - Require better mechanical fixture for Occam so it can be repeatably placed in a given orientation
  - Return to start functionality
    - Sets EKF pose to real pose from magic LED Solve
    - Using waypoint navigator to return sub to starting postion
      - Default (0, 0, -1)
      - Configurable for say a prior to do an intermediate task
    - Potential to use for controls tuning?  Triton thruster odometry tuning?
    - Potential bottom of dive well leds for easier Triton visibility?

**Comment by skhadem** [comment]
Why not use AR markers? Existing ROS packages plus we already have some and I have a start on code for it

**Comment by DrYerzinia** [comment]
I was never clear on how well that worked say for example from across the pool.  You had stated it was very jittery.  The idea with the LEDs is that they are extremely easy to identify in the camera images, and will be clearly visible from across the divewell.  Either way the majority of the work doesn't change.  Its just the pose extraction.
