### ISSUE TITLE
Visual Servoing

### ISSUE THREAD

**Issue by DrYerzinia** [CU-Robosub/cusub#84]
- Axis selection
  - Depth/Drive/Strafe/Yaw
- Goal selection
  - Vertical/Horizontal
  - Pixel Position
  - Percentage
    - Current darknet messages have image with width height for this but is wasteful to shove entire image over

**Comment by skhadem** [comment]
@DrYerzinia How much more work do you think this needs? I know we have a basic bang-bang one in right now
