### ISSUE TITLE
Search Abort Encapsulation

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#88]
Currently we abort the search objective at the task level, a cleaner, more encapsulated solution would be to have the search objective subscribe to some topic passed in as an init param and abort itself on the first publishing.

**Comment by skhadem** [comment]
I am sort of against doing something on first publish, it can lead to weird scenarios and edge cases where something gets published before the subscriber is set up. Maybe use a service so there can be an acknowledge?
