### ISSUE TITLE
Mapper Publishes PoseStamped, Sim Truth Positions are Odom Msgs

### ISSUE THREAD

**Issue by flamma7** [CU-Robosub/cusub#89]
Add a configuration to the mapper to subscribe to truth positions from the sim and publish them on the mapper/_object_ topics as PoseStamped msgs so that all state machine code can be transparent to poses generated from perception stack or taken directly from sim

**Comment by DrYerzinia** [comment]
https://github.com/CU-Robosub/cusub/blob/magic_led/cusub_common/waypoint_navigator/scripts/gazebo_gt_localizer.py

Running:
rosrun waypoint_navigator gazebo_gt_localizer.py __ns:=leviathan

Will give the sub perfect position knowledge in the map frame

Or do you mean object truth positions as well?

So we can feed object truth positions in as the CV data for testing state machine actions give good pose data?

In that case I would probably make a seperate node that takes in the ground truth and feeds that into the mapper the way the localizer feeds into the mapper.

**Comment by flamma7** [comment]
Solved by running
roslaunch mapper mapper.launch **truth_data:=true**
